### ISSUE TITLE
Allow scope-limiting the Schema resolution

### ISSUE THREAD

**Issue by p-louis** [linked-planet/kotlin-insight-wrapper#5]
## Motivation
In order to speed up startup times, it should be possible to reduce the schema resolution to a passed list of object type names.

## Proposed Solution
Add a parameter `objectTypeNameFilter: List<String>? = null` to the init function. 
The schema resolution can then work as follows: 
```kotlin
        val schemas =
            httpClient.get<List<ObjectTypeSchema>>("${JiraConfig.baseUrl}/rest/insight/1.0/objectschema/${JiraConfig.schemaId}/objecttypes/flat")

        return schemas
            .filter { objectTypes?.let { ot -> ot.contains(it.name) } != false }
            .map {
                val attributes =
                    httpClient.get<List<ObjectTypeSchemaAttribute>>("${JiraConfig.baseUrl}/rest/insight/1.0/objecttype/${it.id}/attributes")
                it.copy(attributes = attributes)
            }
```

**Comment by betacore** [comment]
**You can now whitelist the objectSchemas to preload**

- InsightConfig.init("http://localhost:8080", 1, "admin", "admin") // load all objectSchemas
- InsightConfig.init("http://localhost:8080", 1, "admin", "admin", listOf(OBJECTS.Company.name)) // load only listed objectSchemas
